basePath: /v1
host: todo.localhost
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample Todo server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Todo API
  version: "1.0"
paths:
  /api/v1/todo:
    get:
      consumes:
      - application/json
      description: retrieve all todos
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/string'
        "400":
          description: "400"
          schema:
            $ref: '#/definitions/string'
        "404":
          description: "404"
          schema:
            $ref: '#/definitions/string'
      summary: fetchAllTodo fetch all todos
    post:
      consumes:
      - application/json
      description: create todo baased on JSON payload
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/string'
        "400":
          description: "400"
          schema:
            type: string
        "404":
          description: "404"
          schema:
            type: string
      summary: Add a new todo
swagger: "2.0"
